In [1]:
import polars as pl

df = pl.read_csv('../data/camels_gb_v2_climatic_attributes.csv')

In [2]:
df.schema

Schema([('gauge_id', Int64),
        ('p_mean', Float64),
        ('pet_mean', Float64),
        ('aridity', Float64),
        ('p_seasonality', Float64),
        ('frac_snow', Float64),
        ('high_prec_freq', Float64),
        ('high_prec_dur', Float64),
        ('high_prec_timing', String),
        ('low_prec_freq', Float64),
        ('low_prec_dur', Float64),
        ('low_prec_timing', String)])

In [3]:
df.head()

shape: (5, 12)
┌──────────┬────────┬──────────┬─────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ gauge_id ┆ p_mean ┆ pet_mean ┆ aridity ┆ … ┆ high_prec_t ┆ low_prec_fr ┆ low_prec_d ┆ low_prec_t │
│ ---      ┆ ---    ┆ ---      ┆ ---     ┆   ┆ iming       ┆ eq          ┆ ur         ┆ iming      │
│ i64      ┆ f64    ┆ f64      ┆ f64     ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│          ┆        ┆          ┆         ┆   ┆ str         ┆ f64         ┆ f64        ┆ str        │
╞══════════╪════════╪══════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 10002    ┆ 2.35   ┆ 1.33     ┆ 0.56    ┆ … ┆ son         ┆ 205.9       ┆ 3.13       ┆ jja        │
│ 10003    ┆ 2.37   ┆ 1.35     ┆ 0.57    ┆ … ┆ son         ┆ 208.21      ┆ 3.2        ┆ mam        │
│ 1001     ┆ 2.56   ┆ 1.21     ┆ 0.47    ┆ … ┆ son         ┆ 181.56      ┆ 2.92       ┆ jja        │
│ 101002   ┆ 2.37   ┆ 1.81     ┆ 0.76    ┆ … ┆ son         ┆ 243.73      ┆ 4.44       ┆ jja        │
│ 101005   ┆ 2.28   ┆ 1.8      ┆ 0.79    ┆ … ┆ son         ┆ 245.58      ┆ 4.51       ┆ jja        │
└──────────┴────────┴──────────┴─────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [4]:
df.describe()

shape: (9, 13)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ gauge_id  ┆ p_mean   ┆ pet_mean ┆ … ┆ high_prec ┆ low_prec_ ┆ low_prec_ ┆ low_prec_ │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ _timing   ┆ freq      ┆ dur       ┆ timing    │
│ str        ┆ f64       ┆ f64      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆ str       ┆ f64       ┆ f64       ┆ str       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 671.0     ┆ 671.0    ┆ 671.0    ┆ … ┆ 671       ┆ 671.0     ┆ 671.0     ┆ 671       │
│ null_count ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0         │
│ mean       ┆ 43768.396 ┆ 3.151088 ┆ 1.466244 ┆ … ┆ null      ┆ 209.27538 ┆ 3.704441  ┆ null      │
│            ┆ 423       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ std        ┆ 21894.720 ┆ 1.441606 ┆ 0.169615 ┆ … ┆ null      ┆ 31.433463 ┆ 0.505745  ┆ null      │
│            ┆ 374       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 1001.0    ┆ 1.51     ┆ 0.95     ┆ … ┆ NA        ┆ 127.62    ┆ 2.65      ┆ jja       │
│ 25%        ┆ 28015.0   ┆ 2.06     ┆ 1.33     ┆ … ┆ null      ┆ 183.17    ┆ 3.26      ┆ null      │
│ 50%        ┆ 39127.0   ┆ 2.63     ┆ 1.49     ┆ … ┆ null      ┆ 210.1     ┆ 3.68      ┆ null      │
│ 75%        ┆ 56002.0   ┆ 3.86     ┆ 1.62     ┆ … ┆ null      ┆ 239.29    ┆ 4.2       ┆ null      │
│ max        ┆ 107001.0  ┆ 9.76     ┆ 1.84     ┆ … ┆ son       ┆ 259.65    ┆ 4.64      ┆ mam       │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
df.null_count()

shape: (1, 12)
┌──────────┬────────┬──────────┬─────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ gauge_id ┆ p_mean ┆ pet_mean ┆ aridity ┆ … ┆ high_prec_t ┆ low_prec_fr ┆ low_prec_d ┆ low_prec_t │
│ ---      ┆ ---    ┆ ---      ┆ ---     ┆   ┆ iming       ┆ eq          ┆ ur         ┆ iming      │
│ u32      ┆ u32    ┆ u32      ┆ u32     ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│          ┆        ┆          ┆         ┆   ┆ u32         ┆ u32         ┆ u32        ┆ u32        │
╞══════════╪════════╪══════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 0        ┆ 0      ┆ 0        ┆ 0       ┆ … ┆ 0           ┆ 0           ┆ 0          ┆ 0          │
└──────────┴────────┴──────────┴─────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [6]:
(df.null_count() / len(df) * 100).transpose()

shape: (12, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ …        │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘