In [1]:
import polars as pl

df = pl.read_csv('../data/camels_gb_v2_groundwaterwell_attributes.csv')

In [2]:
df.schema

Schema([('gw_well_id', String),
        ('gw_well_name', String),
        ('gw_well_easting', Int64),
        ('gw_well_northing', Int64),
        ('gw_well_datum', Float64),
        ('gw_well_depth', Float64),
        ('aquifer', String),
        ('daily_gwlevel_period_start', String),
        ('daily_gwlevel_period_end', String),
        ('daily_gwlevel_perc_complete', Float64),
        ('monthly_gwlevel_period_start', String),
        ('monthly_gwlevel_period_end', String),
        ('monthly_gwlevel_perc_complete', Float64)])

In [3]:
df.head()

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gw_well_i ┆ gw_well_n ┆ gw_well_e ┆ gw_well_n ┆ … ┆ daily_gwl ┆ monthly_g ┆ monthly_g ┆ monthly_ │
│ d         ┆ ame       ┆ asting    ┆ orthing   ┆   ┆ evel_perc ┆ wlevel_pe ┆ wlevel_pe ┆ gwlevel_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _complete ┆ riod_star ┆ riod_end  ┆ perc_com │
│ str       ┆ str       ┆ i64       ┆ i64       ┆   ┆ ---       ┆ t         ┆ ---       ┆ plete    │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ NY62_4    ┆ ESPLAND   ┆ 368830    ┆ 523010    ┆ … ┆ NaN       ┆ 1976-08-0 ┆ 2024-06-0 ┆ 39.65    │
│           ┆ HILL (NR. ┆           ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ BRAMPTON- ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ AP…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SD53_25   ┆ RED SCAR  ┆ 358600    ┆ 431330    ┆ … ┆ 88.79     ┆ 1980-12-0 ┆ 2025-02-0 ┆ 94.54    │
│           ┆ WOOD      ┆           ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│ SE02_46   ┆ THRUM     ┆ 407710    ┆ 425280    ┆ … ┆ 82.82     ┆ 1977-04-0 ┆ 2025-01-0 ┆ 89.02    │
│           ┆ HALL      ┆           ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│ SE23_4    ┆ SILVER    ┆ 428500    ┆ 434140    ┆ … ┆ NaN       ┆ 1971-03-0 ┆ 2025-01-0 ┆ 87.33    │
│           ┆ BLADES    ┆           ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ ICE RINK  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SE28_28   ┆ BEDALE    ┆ 424600    ┆ 485200    ┆ … ┆ NaN       ┆ 1972-01-0 ┆ 2024-12-0 ┆ 91.35    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
df.describe()

shape: (9, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ gw_well_i ┆ gw_well_n ┆ gw_well_e ┆ … ┆ daily_gwl ┆ monthly_g ┆ monthly_g ┆ monthly_ │
│ ---       ┆ d         ┆ ame       ┆ asting    ┆   ┆ evel_perc ┆ wlevel_pe ┆ wlevel_pe ┆ gwlevel_ │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _complete ┆ riod_star ┆ riod_end  ┆ perc_com │
│           ┆ str       ┆ str       ┆ f64       ┆   ┆ ---       ┆ t         ┆ ---       ┆ plete    │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 55        ┆ 55        ┆ 55.0      ┆ … ┆ 55.0      ┆ 55        ┆ 55        ┆ 55.0     │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 477053.45 ┆ … ┆ NaN       ┆ null      ┆ null      ┆ 85.76636 │
│           ┆           ┆           ┆ 4545      ┆   ┆           ┆           ┆           ┆ 4        │
│ std       ┆ null      ┆ null      ┆ 81026.858 ┆ … ┆ NaN       ┆ null      ┆ null      ┆ 10.90728 │
│           ┆           ┆           ┆ 172       ┆   ┆           ┆           ┆           ┆ 1        │
│ min       ┆ NY62_4    ┆ ABBOTSTON ┆ 338140.0  ┆ … ┆ 22.4      ┆ 1952-09-0 ┆ 2017-10-0 ┆ 39.65    │
│           ┆           ┆ E         ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│ 25%       ┆ null      ┆ null      ┆ 430040.0  ┆ … ┆ 91.16     ┆ null      ┆ null      ┆ 82.25    │
│ 50%       ┆ null      ┆ null      ┆ 464480.0  ┆ … ┆ NaN       ┆ null      ┆ null      ┆ 88.35    │
│ 75%       ┆ null      ┆ null      ┆ 547250.0  ┆ … ┆ NaN       ┆ null      ┆ null      ┆ 92.42    │
│ max       ┆ TQ62_99   ┆ WOODSIDE  ┆ 629320.0  ┆ … ┆ 97.5      ┆ 2017-01-0 ┆ 2025-02-0 ┆ 97.82    │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.null_count()

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gw_well_i ┆ gw_well_n ┆ gw_well_e ┆ gw_well_n ┆ … ┆ daily_gwl ┆ monthly_g ┆ monthly_g ┆ monthly_ │
│ d         ┆ ame       ┆ asting    ┆ orthing   ┆   ┆ evel_perc ┆ wlevel_pe ┆ wlevel_pe ┆ gwlevel_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _complete ┆ riod_star ┆ riod_end  ┆ perc_com │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ t         ┆ ---       ┆ plete    │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆ ---       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
(df.null_count() / len(df) * 100).transpose()

shape: (13, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ …        │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘