In [ ]:
import polars as pl
from project_paths import paths

df = pl.read_csv(paths.camels_data / 'camels_gb_v2_hydrologic_attributes.csv')

In [2]:
df.schema

Schema([('gauge_id', Int64),
        ('q_mean', Float64),
        ('runoff_ratio', Float64),
        ('stream_elas', Float64),
        ('slope_fdc', Float64),
        ('baseflow_index', Float64),
        ('baseflow_index_ceh', Float64),
        ('hfd_mean', Float64),
        ('Q5', Float64),
        ('Q95', Float64),
        ('high_q_freq', Float64),
        ('high_q_dur', Float64),
        ('low_q_freq', Float64),
        ('low_q_dur', Float64),
        ('zero_q_freq', Float64)])

In [3]:
df.head()

shape: (5, 15)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ q_mean ┆ runoff_rat ┆ stream_ela ┆ … ┆ high_q_dur ┆ low_q_fre ┆ low_q_dur ┆ zero_q_fr │
│ ---      ┆ ---    ┆ io         ┆ s          ┆   ┆ ---        ┆ q         ┆ ---       ┆ eq        │
│ i64      ┆ f64    ┆ ---        ┆ ---        ┆   ┆ f64        ┆ ---       ┆ f64       ┆ ---       │
│          ┆        ┆ f64        ┆ f64        ┆   ┆            ┆ f64       ┆           ┆ f64       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 10002    ┆ 1.31   ┆ 0.56       ┆ 1.19       ┆ … ┆ 1.32       ┆ 6.41      ┆ 7.52      ┆ 0.0       │
│ 10003    ┆ 1.32   ┆ 0.55       ┆ 1.37       ┆ … ┆ 1.39       ┆ 8.64      ┆ 9.71      ┆ 0.0       │
│ 1001     ┆ 1.62   ┆ 0.61       ┆ 1.15       ┆ … ┆ 1.52       ┆ 103.48    ┆ 11.74     ┆ 0.0       │
│ 101002   ┆ 0.9    ┆ 0.38       ┆ 1.26       ┆ … ┆ 1.22       ┆ 3.46      ┆ 5.0       ┆ 0.0       │
│ 101005   ┆ 0.79   ┆ 0.35       ┆ 1.35       ┆ … ┆ 1.38       ┆ 0.35      ┆ 2.8       ┆ 0.0       │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [4]:
df.describe()

shape: (9, 16)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ gauge_id  ┆ q_mean   ┆ runoff_ra ┆ … ┆ high_q_du ┆ low_q_fre ┆ low_q_dur ┆ zero_q_fr │
│ ---       ┆ ---       ┆ ---      ┆ tio       ┆   ┆ r         ┆ q         ┆ ---       ┆ eq        │
│ str       ┆ f64       ┆ f64      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ---       │
│           ┆           ┆          ┆ f64       ┆   ┆ f64       ┆ f64       ┆           ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 671.0     ┆ 671.0    ┆ 671.0     ┆ … ┆ 671.0     ┆ 671.0     ┆ 671.0     ┆ 671.0     │
│ null_coun ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 43768.396 ┆ 1.928256 ┆ 0.534694  ┆ … ┆ 2.097228  ┆ 48.844933 ┆ 9.667183  ┆ 0.004173  │
│           ┆ 423       ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ std       ┆ 21894.720 ┆ 1.583483 ┆ 0.244616  ┆ … ┆ 6.086988  ┆ 44.378895 ┆ 11.155471 ┆ 0.035326  │
│           ┆ 374       ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ min       ┆ 1001.0    ┆ 0.09     ┆ 0.03      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 25%       ┆ 28015.0   ┆ 0.75     ┆ 0.36      ┆ … ┆ 1.31      ┆ 8.64      ┆ 5.65      ┆ 0.0       │
│ 50%       ┆ 39127.0   ┆ 1.41     ┆ 0.53      ┆ … ┆ 1.51      ┆ 40.41     ┆ 8.27      ┆ 0.0       │
│ 75%       ┆ 56002.0   ┆ 2.64     ┆ 0.69      ┆ … ┆ 1.93      ┆ 79.0      ┆ 11.1      ┆ 0.0       │
│ max       ┆ 107001.0  ┆ 10.32    ┆ 3.01      ┆ … ┆ 142.18    ┆ 220.77    ┆ 206.71    ┆ 0.53      │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
df.null_count()

shape: (1, 15)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ gauge_id ┆ q_mean ┆ runoff_rat ┆ stream_ela ┆ … ┆ high_q_dur ┆ low_q_fre ┆ low_q_dur ┆ zero_q_fr │
│ ---      ┆ ---    ┆ io         ┆ s          ┆   ┆ ---        ┆ q         ┆ ---       ┆ eq        │
│ u32      ┆ u32    ┆ ---        ┆ ---        ┆   ┆ u32        ┆ ---       ┆ u32       ┆ ---       │
│          ┆        ┆ u32        ┆ u32        ┆   ┆            ┆ u32       ┆           ┆ u32       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0      ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
(df.null_count() / len(df) * 100).transpose()

shape: (15, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ …        │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘