In [ ]:
import polars as pl
from project_paths import paths

df = pl.read_csv(paths.camels_data / 'camels_gb_v2_topographic_attributes.csv')

In [2]:
df.schema

Schema([('gauge_id', Int64),
        ('gauge_name', String),
        ('gauge_lat', Float64),
        ('gauge_lon', Float64),
        ('gauge_easting', Int64),
        ('gauge_northing', Int64),
        ('gauge_elev', Float64),
        ('area', Float64),
        ('dpsbar', Float64),
        ('elev_mean', Int64),
        ('elev_min', Float64),
        ('elev_10', Float64),
        ('elev_50', Float64),
        ('elev_90', Float64),
        ('elev_max', Float64)])

In [3]:
df.head()

shape: (5, 15)
┌──────────┬──────────────────┬───────────┬───────────┬───┬─────────┬─────────┬─────────┬──────────┐
│ gauge_id ┆ gauge_name       ┆ gauge_lat ┆ gauge_lon ┆ … ┆ elev_10 ┆ elev_50 ┆ elev_90 ┆ elev_max │
│ ---      ┆ ---              ┆ ---       ┆ ---       ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---      │
│ i64      ┆ str              ┆ f64       ┆ f64       ┆   ┆ f64     ┆ f64     ┆ f64     ┆ f64      │
╞══════════╪══════════════════╪═══════════╪═══════════╪═══╪═════════╪═════════╪═════════╪══════════╡
│ 10002    ┆ Ugie at          ┆ 57.53     ┆ -1.83     ┆ … ┆ 38.6    ┆ 84.1    ┆ 140.1   ┆ 233.7    │
│          ┆ Inverugie        ┆           ┆           ┆   ┆         ┆         ┆         ┆          │
│ 10003    ┆ Ythan at Ellon   ┆ 57.36     ┆ -2.09     ┆ … ┆ 54.1    ┆ 106.1   ┆ 160.8   ┆ 380.4    │
│ 1001     ┆ Wick at Tarroul  ┆ 58.48     ┆ -3.27     ┆ … ┆ 30.6    ┆ 78.8    ┆ 135.2   ┆ 241.4    │
│ 101002   ┆ Medina at Shide  ┆ 50.69     ┆ -1.29     ┆ … ┆ 26.8    ┆ 56.8    ┆ 98.0    ┆ 193.2    │
│ 101005   ┆ Eastern Yar at   ┆ 50.65     ┆ -1.25     ┆ … ┆ 32.9    ┆ 84.0    ┆ 157.2   ┆ 234.6    │
│          ┆ Budbridge        ┆           ┆           ┆   ┆         ┆         ┆         ┆          │
└──────────┴──────────────────┴───────────┴───────────┴───┴─────────┴─────────┴─────────┴──────────┘

In [4]:
df.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ gauge_id  ┆ gauge_nam ┆ gauge_lat ┆ … ┆ elev_10   ┆ elev_50   ┆ elev_90   ┆ elev_max │
│ ---       ┆ ---       ┆ e         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ ---       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 671.0     ┆ 671       ┆ 671.0     ┆ … ┆ 671.0     ┆ 671.0     ┆ 671.0     ┆ 671.0    │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 43768.396 ┆ null      ┆ 53.365007 ┆ … ┆ 106.32429 ┆ 192.53800 ┆ 310.50491 ┆ 468.3535 │
│           ┆ 423       ┆           ┆           ┆   ┆ 2         ┆ 3         ┆ 8         ┆ 02       │
│ std       ┆ 21894.720 ┆ null      ┆ 2.075101  ┆ … ┆ 83.929684 ┆ 126.99161 ┆ 193.03490 ┆ 298.0827 │
│           ┆ 374       ┆           ┆           ┆   ┆           ┆ 9         ┆ 4         ┆ 11       │
│ min       ┆ 1001.0    ┆ Abhainn   ┆ 50.16     ┆ … ┆ 6.1       ┆ 20.0      ┆ 46.5      ┆ 61.0     │
│           ┆           ┆ a'        ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Bhealaich ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ at        ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Braeva…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 28015.0   ┆ null      ┆ 51.67     ┆ … ┆ 50.0      ┆ 95.4      ┆ 149.2     ┆ 226.1    │
│ 50%       ┆ 39127.0   ┆ null      ┆ 52.86     ┆ … ┆ 82.3      ┆ 152.7     ┆ 256.3     ┆ 391.6    │
│ 75%       ┆ 56002.0   ┆ null      ┆ 55.04     ┆ … ┆ 133.2     ┆ 271.3     ┆ 453.7     ┆ 675.1    │
│ max       ┆ 107001.0  ┆ Ythan at  ┆ 59.11     ┆ … ┆ 573.9     ┆ 680.4     ┆ 942.7     ┆ 1342.6   │
│           ┆           ┆ Ellon     ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.null_count()

shape: (1, 15)
┌──────────┬────────────┬───────────┬───────────┬───┬─────────┬─────────┬─────────┬──────────┐
│ gauge_id ┆ gauge_name ┆ gauge_lat ┆ gauge_lon ┆ … ┆ elev_10 ┆ elev_50 ┆ elev_90 ┆ elev_max │
│ ---      ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---      │
│ u32      ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32     ┆ u32     ┆ u32     ┆ u32      │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪═════════╪═════════╪══════════╡
│ 0        ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 0       ┆ 0       ┆ 0       ┆ 0        │
└──────────┴────────────┴───────────┴───────────┴───┴─────────┴─────────┴─────────┴──────────┘

In [6]:
(df.null_count() / len(df) * 100).transpose()

shape: (15, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ …        │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘